import { Link } from 'react-router-dom'
import { ArrowRight, Dumbbell, Users, Brain, Trophy, CheckCircle, Play, Star, Zap, Clock, Target } from 'lucide-react'
import BMICalculator from '../components/BMICalculator'
import ReviewSlider from '../components/ReviewSlider'

const STATS = [
  { label: 'Active Members', value: '1,200+', icon: Users },
  { label: 'Expert Trainers', value: '25+', icon: Dumbbell },
  { label: 'Classes Daily', value: '30+', icon: Clock },
  { label: 'Success Stories', value: '800+', icon: Trophy },
]

const FEATURES = [
  {
    icon: Brain,
    title: 'AI-Powered Coaching',
    description: 'Get personalized workout and nutrition plans generated by Gemini AI based on your goals and fitness level.',
    color: 'bg-purple-100 dark:bg-purple-900/30 text-purple-600',
  },
  {
    icon: Target,
    title: 'Smart BMI Tracking',
    description: 'Advanced BMI calculator with AI recommendations. Track your progress and get actionable health insights.',
    color: 'bg-brand-100 dark:bg-brand-900/30 text-brand-600',
  },
  {
    icon: Zap,
    title: 'Online Class Booking',
    description: 'Book gym classes in seconds. Real-time availability, instant confirmation, and smart scheduling.',
    color: 'bg-yellow-100 dark:bg-yellow-900/30 text-yellow-600',
  },
  {
    icon: CheckCircle,
    title: 'NayaPay Payments',
    description: 'Hassle-free membership payments via NayaPay. Instant payment confirmation and digital receipts.',
    color: 'bg-green-100 dark:bg-green-900/30 text-green-600',
  },
]

const GALLERY = [
  { url: 'https://images.pexels.com/photos/1552249/pexels-photo-1552249.jpeg?auto=compress&cs=tinysrgb&w=800', alt: 'Weight Training' },
  { url: 'https://images.pexels.com/photos/2294361/pexels-photo-2294361.jpeg?auto=compress&cs=tinysrgb&w=800', alt: 'HIIT Class' },
  { url: 'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=800', alt: 'Cardio' },
  { url: 'https://images.pexels.com/photos/1431282/pexels-photo-1431282.jpeg?auto=compress&cs=tinysrgb&w=800', alt: 'Yoga' },
  { url: 'https://images.pexels.com/photos/2827400/pexels-photo-2827400.jpeg?auto=compress&cs=tinysrgb&w=800', alt: 'Abs Workout' },
  { url: 'https://images.pexels.com/photos/4162491/pexels-photo-4162491.jpeg?auto=compress&cs=tinysrgb&w=800', alt: 'Cycling' },
]

export default function Home() {
  return (
    <div className="page-enter">
      {/* =====================
          HERO SECTION
      ===================== */}
      <section className="relative min-h-screen flex items-center overflow-hidden">
        {/* Background Image */}
        <div className="absolute inset-0">
          <img
            src="https://images.pexels.com/photos/1552249/pexels-photo-1552249.jpeg?auto=compress&cs=tinysrgb&w=1200"
            alt="Hero"
            fetchpriority="high"
            loading="eager"
            decoding="async"
            className="w-full h-full object-cover object-center"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-dark-900/95 via-dark-900/80 to-dark-900/40" />
        </div>

        {/* Animated decoration */}
        <div className="absolute right-10 top-1/4 w-64 h-64 bg-brand-500/10 rounded-full blur-3xl animate-pulse-slow hidden lg:block" />
        <div className="absolute right-32 bottom-1/4 w-32 h-32 bg-brand-500/20 rounded-full blur-2xl animate-pulse-slow hidden lg:block" />

        <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-16">
          <div className="max-w-3xl">
            {/* Badge */}
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-brand-500/20 border border-brand-500/40 rounded-full mb-6 animate-fade-in">
              <Zap size={14} className="text-brand-400" />
              <span className="text-brand-300 text-sm font-body font-semibold">AI-Powered Gym Management</span>
            </div>

            <h1 className="font-display text-6xl sm:text-7xl md:text-8xl text-white leading-none mb-6 tracking-wide animate-slide-up">
              FORGE YOUR
              <br />
              <span className="text-brand-500">STRONGER</span>
              <br />
              SELF
            </h1>

            <p className="text-gray-300 font-body text-lg md:text-xl leading-relaxed mb-10 max-w-xl">
              Pakistan's first AI-powered gym. Smart workout plans, real-time coaching, and seamless management — all in one place.
            </p>

            <div className="flex flex-wrap gap-4">
              <Link to="/register" className="btn-primary text-base px-8 py-4 shadow-2xl shadow-brand-500/30">
                Start Free Trial <ArrowRight size={18} />
              </Link>
              <Link to="/plans" className="flex items-center gap-2 px-8 py-4 bg-white/10 backdrop-blur-sm
              text-white font-heading font-semibold rounded-lg border border-white/20 hover:bg-white/20 transition-all">
                <Play size={18} /> View Plans
              </Link>
            </div>

            {/* Mini Stats */}
            <div className="flex flex-wrap gap-6 mt-12">
              {[['1200+', 'Members'], ['25+', 'Trainers'], ['5★', 'Rated']].map(([val, label]) => (
                <div key={label} className="text-center">
                  <p className="font-display text-3xl text-brand-400">{val}</p>
                  <p className="text-gray-400 text-xs font-body uppercase tracking-wider">{label}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Scroll indicator */}
        <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 animate-bounce">
          <span className="text-gray-400 text-xs font-body">Scroll Down</span>
          <div className="w-5 h-8 border-2 border-gray-400 rounded-full flex justify-center pt-1.5">
            <div className="w-1 h-2 bg-brand-500 rounded-full animate-bounce" />
          </div>
        </div>
      </section>

      {/* =====================
          STATS BANNER
      ===================== */}
      <section className="bg-dark-800 dark:bg-dark-900 py-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {STATS.map(({ label, value, icon: Icon }) => (
              <div key={label} className="flex items-center gap-4 text-center md:text-left justify-center md:justify-start">
                <div className="w-12 h-12 bg-brand-500/20 rounded-xl flex items-center justify-center flex-shrink-0 hidden md:flex">
                  <Icon size={22} className="text-brand-400" />
                </div>
                <div>
                  <p className="font-display text-3xl text-brand-400">{value}</p>
                  <p className="text-gray-400 text-sm font-body">{label}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* =====================
          ABOUT SECTION
      ===================== */}
      <section className="py-24 bg-white dark:bg-dark-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            {/* Images Grid */}
            <div className="grid grid-cols-2 gap-4 relative">
              <div className="space-y-4">
                <img loading="lazy" decoding="async" src="https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=600"
                  alt="Gym" className="w-full h-56 object-cover rounded-2xl" />
                <img loading="lazy" decoding="async" src="https://images.pexels.com/photos/2827400/pexels-photo-2827400.jpeg?auto=compress&cs=tinysrgb&w=600"
                  alt="Training" className="w-full h-36 object-cover rounded-2xl" />
              </div>
              <div className="space-y-4 pt-8">
                <img loading="lazy" decoding="async" src="https://images.pexels.com/photos/4162491/pexels-photo-4162491.jpeg?auto=compress&cs=tinysrgb&w=600"
                  alt="Class" className="w-full h-36 object-cover rounded-2xl" />
                <img loading="lazy" decoding="async" src="https://images.pexels.com/photos/2294361/pexels-photo-2294361.jpeg?auto=compress&cs=tinysrgb&w=600"
                  alt="HIIT" className="w-full h-56 object-cover rounded-2xl" />
              </div>
              {/* Badge overlay */}
              <div className="absolute -bottom-6 left-1/2 -translate-x-1/2 bg-brand-500 text-white
              px-6 py-3 rounded-2xl shadow-xl shadow-brand-500/40 font-heading font-bold whitespace-nowrap">
                🏆 Lahore's Best Gym 2024
              </div>
            </div>

            {/* Content */}
            <div className="space-y-6">
              <div>
                <p className="text-brand-500 font-heading font-semibold text-sm uppercase tracking-widest mb-3">
                  ABOUT POWERFIT
                </p>
                <h2 className="section-title">
                  WHERE SCIENCE
                  <br />
                  MEETS <span className="text-brand-500">STRENGTH</span>
                </h2>
              </div>
              <p className="text-gray-600 dark:text-gray-400 font-body leading-relaxed">
                PowerFit is Pakistan's premier AI-powered gym management system. We combine cutting-edge artificial
                intelligence with world-class training facilities to deliver a truly personalized fitness experience.
              </p>
              <div className="space-y-3">
                {[
                  'AI-generated personalized workout plans',
                  'Certified professional trainers',
                  'Smart class scheduling and booking',
                  'Real-time progress tracking and analytics',
                  'Secure NayaPay payment integration',
                ].map(item => (
                  <div key={item} className="flex items-center gap-3">
                    <CheckCircle size={18} className="text-brand-500 flex-shrink-0" />
                    <span className="text-gray-700 dark:text-gray-300 font-body text-sm">{item}</span>
                  </div>
                ))}
              </div>
              <Link to="/about" className="btn-primary inline-flex">
                Learn More <ArrowRight size={16} />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* =====================
          FEATURES
      ===================== */}
      <section className="py-24 bg-gray-50 dark:bg-dark-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <p className="text-brand-500 font-heading font-semibold text-sm uppercase tracking-widest mb-3">WHY POWERFIT</p>
            <h2 className="section-title mb-4">
              SMART GYM <br />
              <span className="text-brand-500">FEATURES</span>
            </h2>
            <p className="section-subtitle mx-auto text-center">
              Everything you need for a complete, AI-enhanced fitness management experience
            </p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {FEATURES.map(({ icon: Icon, title, description, color }) => (
              <div key={title} className="card-hover p-6 group">
                <div className={`w-14 h-14 rounded-2xl flex items-center justify-center mb-5 ${color}`}>
                  <Icon size={26} />
                </div>
                <h3 className="font-heading font-bold text-lg text-dark-800 dark:text-white mb-3">{title}</h3>
                <p className="text-gray-500 dark:text-gray-400 font-body text-sm leading-relaxed">{description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* =====================
          BMI CALCULATOR
      ===================== */}
      <section className="py-24 bg-white dark:bg-dark-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div className="space-y-6">
              <p className="text-brand-500 font-heading font-semibold text-sm uppercase tracking-widest">
                AI + BMI CALCULATOR
              </p>
              <h2 className="section-title">
                KNOW YOUR
                <br />
                <span className="text-brand-500">BODY</span>
              </h2>
              <p className="text-gray-600 dark:text-gray-400 font-body leading-relaxed">
                Calculate your BMI instantly and get AI-powered workout recommendations tailored to your body metrics and goals.
              </p>
              <div className="grid grid-cols-3 gap-4">
                {[['BMI', 'Instant'], ['AI Plan', 'Personalized'], ['Goals', 'Achievable']].map(([t, d]) => (
                  <div key={t} className="p-4 bg-brand-50 dark:bg-brand-900/20 rounded-xl text-center">
                    <p className="font-heading font-bold text-dark-800 dark:text-white">{t}</p>
                    <p className="text-xs text-brand-600 font-body">{d}</p>
                  </div>
                ))}
              </div>
            </div>
            <BMICalculator />
          </div>
        </div>
      </section>

      {/* =====================
          GALLERY
      ===================== */}
      <section className="py-24 bg-gray-50 dark:bg-dark-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <p className="text-brand-500 font-heading font-semibold text-sm uppercase tracking-widest mb-3">OUR FACILITY</p>
            <h2 className="section-title">WORLD CLASS <span className="text-brand-500">GYM</span></h2>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {GALLERY.map(({ url, alt }) => (
              <div key={alt} className="group overflow-hidden rounded-2xl aspect-video">
                <img loading="lazy" decoding="async" src={url} alt={alt} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* =====================
          REVIEWS
      ===================== */}
      <section className="py-24 bg-white dark:bg-dark-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <p className="text-brand-500 font-heading font-semibold text-sm uppercase tracking-widest mb-3">TESTIMONIALS</p>
            <h2 className="section-title">
              WHAT OUR <span className="text-brand-500">MEMBERS</span>
              <br />SAY
            </h2>
            <div className="flex items-center justify-center gap-1 mt-4">
              {[...Array(5)].map((_, i) => <Star key={i} size={20} className="text-yellow-400 fill-yellow-400" />)}
              <span className="ml-2 text-gray-500 font-body text-sm">4.9/5 from 800+ reviews</span>
            </div>
          </div>
          <ReviewSlider />
        </div>
      </section>

      {/* =====================
          CTA
      ===================== */}
      <section className="py-24 relative overflow-hidden">
        <div className="absolute inset-0">
          <img
            src="https://images.pexels.com/photos/1552249/pexels-photo-1552249.jpeg?auto=compress&cs=tinysrgb&w=1200"
            alt="CTA Background"
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-dark-900/90" />
        </div>
        <div className="relative z-10 max-w-4xl mx-auto px-4 text-center">
          <p className="text-brand-400 font-heading font-semibold text-sm uppercase tracking-widest mb-4">START TODAY</p>
          <h2 className="font-display text-5xl md:text-7xl text-white mb-6 tracking-wide">
            YOUR BEST BODY <br />
            <span className="text-brand-500">STARTS NOW</span>
          </h2>
          <p className="text-gray-300 font-body text-lg mb-10 max-w-lg mx-auto">
            Join 1,200+ members already transforming their lives with PowerFit AI
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link to="/register" className="btn-primary text-lg px-10 py-4">
              Join PowerFit <ArrowRight size={20} />
            </Link>
            <Link to="/plans" className="flex items-center gap-2 px-10 py-4 bg-white/10 text-white
            font-heading font-semibold rounded-lg border border-white/30 hover:bg-white/20 transition-all text-lg">
              See Plans
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}
